#pragma once
#include <vulkan/vulkan_core.h>

constexpr bool vkuAccessBitIsRead(const VkAccessFlagBits access) {
  switch (access) {
    case VK_ACCESS_INDIRECT_COMMAND_READ_BIT:
    case VK_ACCESS_INDEX_READ_BIT:
    case VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT:
    case VK_ACCESS_UNIFORM_READ_BIT:
    case VK_ACCESS_INPUT_ATTACHMENT_READ_BIT:
    case VK_ACCESS_SHADER_READ_BIT:
    case VK_ACCESS_COLOR_ATTACHMENT_READ_BIT:
    case VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT:
    case VK_ACCESS_TRANSFER_READ_BIT:
    case VK_ACCESS_HOST_READ_BIT:
    case VK_ACCESS_MEMORY_READ_BIT:
    case VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT:
    case VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT:
    case VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT:
    case VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR:
    case VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT:
    case VK_ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR:
    case VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_EXT:
      return true;
    default:
      return false;
  }
}

constexpr bool vkuAccessIsRead(const VkAccessFlags access) {
  constexpr VkAccessFlags read =
    VK_ACCESS_INDIRECT_COMMAND_READ_BIT |
    VK_ACCESS_INDEX_READ_BIT |
    VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT |
    VK_ACCESS_UNIFORM_READ_BIT |
    VK_ACCESS_INPUT_ATTACHMENT_READ_BIT |
    VK_ACCESS_SHADER_READ_BIT |
    VK_ACCESS_COLOR_ATTACHMENT_READ_BIT |
    VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT |
    VK_ACCESS_TRANSFER_READ_BIT |
    VK_ACCESS_HOST_READ_BIT |
    VK_ACCESS_MEMORY_READ_BIT |
    VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT |
    VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT |
    VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT |
    VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR |
    VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT |
    VK_ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR |
    VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_EXT;
  return read & access;
}

constexpr bool vkuAccessBitIsWrite(const VkAccessFlagBits access) {
  switch (access) {
    case VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_EXT:
    case VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR:
    case VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT:
    case VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT:
    case VK_ACCESS_SHADER_WRITE_BIT:
    case VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT:
    case VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT:
    case VK_ACCESS_TRANSFER_WRITE_BIT:
    case VK_ACCESS_HOST_WRITE_BIT:
    case VK_ACCESS_MEMORY_WRITE_BIT:
      return true;
    default:
      return false;
  }
}

constexpr bool vkuAccessIsWrite(const VkAccessFlags access) {
  constexpr VkAccessFlags write =
    VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_EXT |
    VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR |
    VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT |
    VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT |
    VK_ACCESS_SHADER_WRITE_BIT |
    VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
    VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT |
    VK_ACCESS_TRANSFER_WRITE_BIT |
    VK_ACCESS_HOST_WRITE_BIT |
    VK_ACCESS_MEMORY_WRITE_BIT;
  return write & access;
}